// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat-common/src/main/java/protobuf/RpcMsg.proto

package model.chat;

public final class RpcMsg {
  private RpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msg_id = 1;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <code>string msg_id = 1;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>int64 from_uid = 2;</code>
     * @return The fromUid.
     */
    long getFromUid();

    /**
     * <code>int64 to_uid = 3;</code>
     * @return The toUid.
     */
    long getToUid();

    /**
     * <code>int32 format = 4;</code>
     * @return The format.
     */
    int getFormat();

    /**
     * <code>int32 msg_type = 5;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <code>int32 chat_type = 6;</code>
     * @return The chatType.
     */
    int getChatType();

    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string body = 8;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <code>string body = 8;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @return A list containing the toUidList.
     */
    java.util.List<java.lang.Long> getToUidListList();
    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @return The count of toUidList.
     */
    int getToUidListCount();
    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @param index The index of the element to return.
     * @return The toUidList at the given index.
     */
    long getToUidList(int index);
  }
  /**
   * Protobuf type {@code Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      msgId_ = "";
      body_ = "";
      toUidList_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 16: {

              fromUid_ = input.readInt64();
              break;
            }
            case 24: {

              toUid_ = input.readInt64();
              break;
            }
            case 32: {

              format_ = input.readInt32();
              break;
            }
            case 40: {

              msgType_ = input.readInt32();
              break;
            }
            case 48: {

              chatType_ = input.readInt32();
              break;
            }
            case 56: {

              timestamp_ = input.readInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                toUidList_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              toUidList_.addLong(input.readInt64());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                toUidList_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                toUidList_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          toUidList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.chat.RpcMsg.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.chat.RpcMsg.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.chat.RpcMsg.Msg.class, model.chat.RpcMsg.Msg.Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <code>string msg_id = 1;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msg_id = 1;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_UID_FIELD_NUMBER = 2;
    private long fromUid_;
    /**
     * <code>int64 from_uid = 2;</code>
     * @return The fromUid.
     */
    public long getFromUid() {
      return fromUid_;
    }

    public static final int TO_UID_FIELD_NUMBER = 3;
    private long toUid_;
    /**
     * <code>int64 to_uid = 3;</code>
     * @return The toUid.
     */
    public long getToUid() {
      return toUid_;
    }

    public static final int FORMAT_FIELD_NUMBER = 4;
    private int format_;
    /**
     * <code>int32 format = 4;</code>
     * @return The format.
     */
    public int getFormat() {
      return format_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <code>int32 msg_type = 5;</code>
     * @return The msgType.
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 6;
    private int chatType_;
    /**
     * <code>int32 chat_type = 6;</code>
     * @return The chatType.
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int BODY_FIELD_NUMBER = 8;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 8;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 8;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_UID_LIST_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.LongList toUidList_;
    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @return A list containing the toUidList.
     */
    public java.util.List<java.lang.Long>
        getToUidListList() {
      return toUidList_;
    }
    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @return The count of toUidList.
     */
    public int getToUidListCount() {
      return toUidList_.size();
    }
    /**
     * <code>repeated int64 to_uid_list = 9;</code>
     * @param index The index of the element to return.
     * @return The toUidList at the given index.
     */
    public long getToUidList(int index) {
      return toUidList_.getLong(index);
    }
    private int toUidListMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (fromUid_ != 0L) {
        output.writeInt64(2, fromUid_);
      }
      if (toUid_ != 0L) {
        output.writeInt64(3, toUid_);
      }
      if (format_ != 0) {
        output.writeInt32(4, format_);
      }
      if (msgType_ != 0) {
        output.writeInt32(5, msgType_);
      }
      if (chatType_ != 0) {
        output.writeInt32(6, chatType_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(7, timestamp_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, body_);
      }
      if (getToUidListList().size() > 0) {
        output.writeUInt32NoTag(74);
        output.writeUInt32NoTag(toUidListMemoizedSerializedSize);
      }
      for (int i = 0; i < toUidList_.size(); i++) {
        output.writeInt64NoTag(toUidList_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (fromUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromUid_);
      }
      if (toUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, toUid_);
      }
      if (format_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, format_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgType_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, chatType_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, body_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toUidList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(toUidList_.getLong(i));
        }
        size += dataSize;
        if (!getToUidListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        toUidListMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.chat.RpcMsg.Msg)) {
        return super.equals(obj);
      }
      model.chat.RpcMsg.Msg other = (model.chat.RpcMsg.Msg) obj;

      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (getFromUid()
          != other.getFromUid()) return false;
      if (getToUid()
          != other.getToUid()) return false;
      if (getFormat()
          != other.getFormat()) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (getChatType()
          != other.getChatType()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!getToUidListList()
          .equals(other.getToUidListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + FROM_UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromUid());
      hash = (37 * hash) + TO_UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToUid());
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (getToUidListCount() > 0) {
        hash = (37 * hash) + TO_UID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getToUidListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.chat.RpcMsg.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.chat.RpcMsg.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.chat.RpcMsg.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.chat.RpcMsg.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static model.chat.RpcMsg.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.chat.RpcMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.chat.RpcMsg.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        model.chat.RpcMsg.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.chat.RpcMsg.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.chat.RpcMsg.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.chat.RpcMsg.Msg.class, model.chat.RpcMsg.Msg.Builder.class);
      }

      // Construct using model.chat.RpcMsg.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = "";

        fromUid_ = 0L;

        toUid_ = 0L;

        format_ = 0;

        msgType_ = 0;

        chatType_ = 0;

        timestamp_ = 0L;

        body_ = "";

        toUidList_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.chat.RpcMsg.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public model.chat.RpcMsg.Msg getDefaultInstanceForType() {
        return model.chat.RpcMsg.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public model.chat.RpcMsg.Msg build() {
        model.chat.RpcMsg.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.chat.RpcMsg.Msg buildPartial() {
        model.chat.RpcMsg.Msg result = new model.chat.RpcMsg.Msg(this);
        int from_bitField0_ = bitField0_;
        result.msgId_ = msgId_;
        result.fromUid_ = fromUid_;
        result.toUid_ = toUid_;
        result.format_ = format_;
        result.msgType_ = msgType_;
        result.chatType_ = chatType_;
        result.timestamp_ = timestamp_;
        result.body_ = body_;
        if (((bitField0_ & 0x00000001) != 0)) {
          toUidList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.toUidList_ = toUidList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.chat.RpcMsg.Msg) {
          return mergeFrom((model.chat.RpcMsg.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.chat.RpcMsg.Msg other) {
        if (other == model.chat.RpcMsg.Msg.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.getFromUid() != 0L) {
          setFromUid(other.getFromUid());
        }
        if (other.getToUid() != 0L) {
          setToUid(other.getToUid());
        }
        if (other.getFormat() != 0) {
          setFormat(other.getFormat());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.toUidList_.isEmpty()) {
          if (toUidList_.isEmpty()) {
            toUidList_ = other.toUidList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToUidListIsMutable();
            toUidList_.addAll(other.toUidList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        model.chat.RpcMsg.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (model.chat.RpcMsg.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgId_ = "";
      /**
       * <code>string msg_id = 1;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg_id = 1;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg_id = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msg_id = 1;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private long fromUid_ ;
      /**
       * <code>int64 from_uid = 2;</code>
       * @return The fromUid.
       */
      public long getFromUid() {
        return fromUid_;
      }
      /**
       * <code>int64 from_uid = 2;</code>
       * @param value The fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUid(long value) {
        
        fromUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from_uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUid() {
        
        fromUid_ = 0L;
        onChanged();
        return this;
      }

      private long toUid_ ;
      /**
       * <code>int64 to_uid = 3;</code>
       * @return The toUid.
       */
      public long getToUid() {
        return toUid_;
      }
      /**
       * <code>int64 to_uid = 3;</code>
       * @param value The toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUid(long value) {
        
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to_uid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUid() {
        
        toUid_ = 0L;
        onChanged();
        return this;
      }

      private int format_ ;
      /**
       * <code>int32 format = 4;</code>
       * @return The format.
       */
      public int getFormat() {
        return format_;
      }
      /**
       * <code>int32 format = 4;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(int value) {
        
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 format = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        
        format_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msg_type = 5;</code>
       * @return The msgType.
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msg_type = 5;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msg_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <code>int32 chat_type = 6;</code>
       * @return The chatType.
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <code>int32 chat_type = 6;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(int value) {
        
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chat_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 7;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 8;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 8;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 8;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 8;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList toUidList_ = emptyLongList();
      private void ensureToUidListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          toUidList_ = mutableCopy(toUidList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @return A list containing the toUidList.
       */
      public java.util.List<java.lang.Long>
          getToUidListList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(toUidList_) : toUidList_;
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @return The count of toUidList.
       */
      public int getToUidListCount() {
        return toUidList_.size();
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @param index The index of the element to return.
       * @return The toUidList at the given index.
       */
      public long getToUidList(int index) {
        return toUidList_.getLong(index);
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @param index The index to set the value at.
       * @param value The toUidList to set.
       * @return This builder for chaining.
       */
      public Builder setToUidList(
          int index, long value) {
        ensureToUidListIsMutable();
        toUidList_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @param value The toUidList to add.
       * @return This builder for chaining.
       */
      public Builder addToUidList(long value) {
        ensureToUidListIsMutable();
        toUidList_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @param values The toUidList to add.
       * @return This builder for chaining.
       */
      public Builder addAllToUidList(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureToUidListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toUidList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 to_uid_list = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUidList() {
        toUidList_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final model.chat.RpcMsg.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.chat.RpcMsg.Msg();
    }

    public static model.chat.RpcMsg.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.chat.RpcMsg.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/chat-common/src/main/java/protobuf/Rpc" +
      "Msg.proto\"\242\001\n\003Msg\022\016\n\006msg_id\030\001 \001(\t\022\020\n\010fro" +
      "m_uid\030\002 \001(\003\022\016\n\006to_uid\030\003 \001(\003\022\016\n\006format\030\004 " +
      "\001(\005\022\020\n\010msg_type\030\005 \001(\005\022\021\n\tchat_type\030\006 \001(\005" +
      "\022\021\n\ttimestamp\030\007 \001(\003\022\014\n\004body\030\010 \001(\t\022\023\n\013to_" +
      "uid_list\030\t \003(\003B\024\n\nmodel.chatB\006RpcMsgb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "MsgId", "FromUid", "ToUid", "Format", "MsgType", "ChatType", "Timestamp", "Body", "ToUidList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
